/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

/**
 *
 * @author IQBAL
 */
public class tampilan_menu_tambahan extends javax.swing.JFrame {

    /**
     * Creates new form tampilan_menu_tambahan
     */
    public tampilan_menu_tambahan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahan1 = new javax.swing.JLabel();
        tambahan2 = new javax.swing.JLabel();
        tambahan3 = new javax.swing.JLabel();
        tambahan4 = new javax.swing.JLabel();
        namaTambahan1 = new javax.swing.JLabel();
        namaTambahan3 = new javax.swing.JLabel();
        namaTambahan4 = new javax.swing.JLabel();
        namaTambahan2 = new javax.swing.JLabel();
        tambahan5 = new javax.swing.JLabel();
        tambahan6 = new javax.swing.JLabel();
        tambahan7 = new javax.swing.JLabel();
        tambahan8 = new javax.swing.JLabel();
        namaTambahan5 = new javax.swing.JLabel();
        namaTambahan7 = new javax.swing.JLabel();
        namaTambahan8 = new javax.swing.JLabel();
        namaTambahan6 = new javax.swing.JLabel();
        xMakanan = new javax.swing.JButton();
        xMinuman = new javax.swing.JButton();
        xTambahan = new javax.swing.JButton();
        hargaTambahan1 = new javax.swing.JLabel();
        hargaTambahan2 = new javax.swing.JLabel();
        hargaTambahan3 = new javax.swing.JLabel();
        hargaTambahan4 = new javax.swing.JLabel();
        inputanTambahan1 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        inputanTambahan3 = new javax.swing.JButton();
        inputanTambahan4 = new javax.swing.JButton();
        hargaTambahan8 = new javax.swing.JLabel();
        hargaTambahan7 = new javax.swing.JLabel();
        hargaTambahan6 = new javax.swing.JLabel();
        hargaTambahan5 = new javax.swing.JLabel();
        inputanTambahan5 = new javax.swing.JButton();
        inputanTambahan6 = new javax.swing.JButton();
        inputanTambahan7 = new javax.swing.JButton();
        inputanTambahan8 = new javax.swing.JButton();
        xPesanan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tambahan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_menu/kulit crispy.jpg"))); // NOI18N
        getContentPane().add(tambahan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 66, -1, -1));

        tambahan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_menu/cah jamur.jpg"))); // NOI18N
        getContentPane().add(tambahan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 66, -1, -1));

        tambahan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_menu/cah kangkung.jpg"))); // NOI18N
        getContentPane().add(tambahan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 66, -1, -1));

        tambahan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_menu/nasi.jpg"))); // NOI18N
        getContentPane().add(tambahan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 66, -1, -1));

        namaTambahan1.setText("   Kulit Crispy");
        getContentPane().add(namaTambahan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 259, 71, -1));

        namaTambahan3.setText("Cah Kangkung");
        getContentPane().add(namaTambahan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 259, 90, -1));

        namaTambahan4.setText("   Nasi Putih");
        getContentPane().add(namaTambahan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 259, 71, -1));

        namaTambahan2.setText("   Cah Jamur");
        getContentPane().add(namaTambahan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 259, 71, -1));

        tambahan5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_menu/tahu goreng.jpg"))); // NOI18N
        getContentPane().add(tambahan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 352, -1, -1));

        tambahan6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_menu/brokoli crispy.jpg"))); // NOI18N
        getContentPane().add(tambahan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 352, -1, -1));

        tambahan7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_menu/krupuk.jpg"))); // NOI18N
        getContentPane().add(tambahan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 352, -1, -1));

        tambahan8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_menu/terong penyet.jpg"))); // NOI18N
        getContentPane().add(tambahan8, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 352, -1, -1));

        namaTambahan5.setText(" Tahu Goreng");
        getContentPane().add(namaTambahan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 544, 80, -1));

        namaTambahan7.setText("      Krupuk");
        getContentPane().add(namaTambahan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 544, 71, -1));

        namaTambahan8.setText("Terong Penyet");
        getContentPane().add(namaTambahan8, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 544, -1, -1));

        namaTambahan6.setText(" Brokoli Crispy");
        getContentPane().add(namaTambahan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 544, 80, -1));

        xMakanan.setText("Makanan");
        xMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xMakananActionPerformed(evt);
            }
        });
        getContentPane().add(xMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 11, 105, 44));

        xMinuman.setText("Minuman");
        xMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xMinumanActionPerformed(evt);
            }
        });
        getContentPane().add(xMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 11, 105, 44));

        xTambahan.setText("Tambahan");
        xTambahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xTambahanActionPerformed(evt);
            }
        });
        getContentPane().add(xTambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 11, 105, 44));

        hargaTambahan1.setText("   Rp. 9.500");
        getContentPane().add(hargaTambahan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 279, 71, -1));

        hargaTambahan2.setText("    Rp. 9000");
        getContentPane().add(hargaTambahan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 279, 71, -1));

        hargaTambahan3.setText("     Rp. 8000");
        getContentPane().add(hargaTambahan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 279, 80, -1));

        hargaTambahan4.setText("   Rp. 4000");
        getContentPane().add(hargaTambahan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 279, 71, -1));

        inputanTambahan1.setText("Tambah");
        inputanTambahan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputanTambahan1ActionPerformed(evt);
            }
        });
        getContentPane().add(inputanTambahan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 299, -1, -1));

        jButton17.setText("Tambah");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 299, -1, -1));

        inputanTambahan3.setText("Tambah");
        getContentPane().add(inputanTambahan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 299, 80, -1));

        inputanTambahan4.setText("Tambah");
        getContentPane().add(inputanTambahan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 299, -1, -1));

        hargaTambahan8.setText("     Rp. 7000");
        getContentPane().add(hargaTambahan8, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 569, 71, -1));

        hargaTambahan7.setText("    Rp. 3000");
        getContentPane().add(hargaTambahan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 569, 71, -1));

        hargaTambahan6.setText("     Rp. 7000");
        getContentPane().add(hargaTambahan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 569, 71, -1));

        hargaTambahan5.setText("    Rp. 5000");
        getContentPane().add(hargaTambahan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 569, 71, -1));

        inputanTambahan5.setText("Tambah");
        getContentPane().add(inputanTambahan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 589, -1, -1));

        inputanTambahan6.setText("Tambah");
        getContentPane().add(inputanTambahan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 589, -1, -1));

        inputanTambahan7.setText("Tambah");
        getContentPane().add(inputanTambahan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 589, -1, -1));

        inputanTambahan8.setText("Tambah");
        getContentPane().add(inputanTambahan8, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 589, -1, -1));

        xPesanan.setText("Pesanan");
        xPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPesananActionPerformed(evt);
            }
        });
        getContentPane().add(xPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 11, 105, 44));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_menu/bckgrd.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 840, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xMakananActionPerformed
        // TODO add your handling code here:
        tampilan_menu_makanan makanan = new tampilan_menu_makanan();
        makanan.setVisible(true);
        dispose();
    }//GEN-LAST:event_xMakananActionPerformed

    private void xMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xMinumanActionPerformed
        // TODO add your handling code here:
        tampilan_menu_minuman minuman = new tampilan_menu_minuman();
        minuman.setVisible(true);
        dispose();
    }//GEN-LAST:event_xMinumanActionPerformed

    private void xTambahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xTambahanActionPerformed
        // TODO add your handling code here:
        tampilan_menu_tambahan tambahan = new tampilan_menu_tambahan();
        tambahan.setVisible(true);
        dispose();
    }//GEN-LAST:event_xTambahanActionPerformed

    private void inputanTambahan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputanTambahan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputanTambahan1ActionPerformed

    private void xPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xPesananActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilan_menu_tambahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilan_menu_tambahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilan_menu_tambahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilan_menu_tambahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilan_menu_tambahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hargaTambahan1;
    private javax.swing.JLabel hargaTambahan2;
    private javax.swing.JLabel hargaTambahan3;
    private javax.swing.JLabel hargaTambahan4;
    private javax.swing.JLabel hargaTambahan5;
    private javax.swing.JLabel hargaTambahan6;
    private javax.swing.JLabel hargaTambahan7;
    private javax.swing.JLabel hargaTambahan8;
    private javax.swing.JButton inputanTambahan1;
    private javax.swing.JButton inputanTambahan3;
    private javax.swing.JButton inputanTambahan4;
    private javax.swing.JButton inputanTambahan5;
    private javax.swing.JButton inputanTambahan6;
    private javax.swing.JButton inputanTambahan7;
    private javax.swing.JButton inputanTambahan8;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel namaTambahan1;
    private javax.swing.JLabel namaTambahan2;
    private javax.swing.JLabel namaTambahan3;
    private javax.swing.JLabel namaTambahan4;
    private javax.swing.JLabel namaTambahan5;
    private javax.swing.JLabel namaTambahan6;
    private javax.swing.JLabel namaTambahan7;
    private javax.swing.JLabel namaTambahan8;
    private javax.swing.JLabel tambahan1;
    private javax.swing.JLabel tambahan2;
    private javax.swing.JLabel tambahan3;
    private javax.swing.JLabel tambahan4;
    private javax.swing.JLabel tambahan5;
    private javax.swing.JLabel tambahan6;
    private javax.swing.JLabel tambahan7;
    private javax.swing.JLabel tambahan8;
    private javax.swing.JButton xMakanan;
    private javax.swing.JButton xMinuman;
    private javax.swing.JButton xPesanan;
    private javax.swing.JButton xTambahan;
    // End of variables declaration//GEN-END:variables
}
